name:                od-crawler
version:             0.1.0.0
github:              "agourlay/od-crawler"
license:             BSD3
author:              "agourlay"
maintainer:          "agourlay"
copyright:           "2019 Arnaud Gourlay"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/agourlay/od-crawler#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2
- uri-encode >= 1.5.0.5
- http-conduit >= 2.3.2
- html-conduit >= 1.3.2
- xml-conduit >= 1.8.0.1
- text >= 1.2.3.1
- unordered-containers >= 0.2.9.0
- directory >= 1.3.1.5
- async >= 2.2.1
- ekg >= 0.4.0.15
- ekg-core >= 0.1.1.6
- clock >= 0.7.2
- optparse-applicative >= 0.14.3.0
- split

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Werror
  - -fno-warn-orphans
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  od-crawler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - od-crawler

tests:
  od-indexer-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - od-crawler
    - hspec >= 2.5.5
    - hspec-discover
    - raw-strings-qq >= 1.1
