name:                od-crawler
version:             0.1.0.0
github:              "agourlay/od-crawler"
license:             BSD3
author:              "agourlay"
maintainer:          "agourlay"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/od-indexer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  od-crawler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - od-crawler
    - bytestring >= 0.10.8.2
    - uri-encode >= 1.5.0.5
    - http-conduit >= 2.3.2
    - html-conduit >= 1.3.1
    - xml-conduit >= 1.8.0
    - text >= 1.2.3.0
    - optparse-applicative >= 0.14.2.0
    - unordered-containers >= 0.2.9.0
    - directory >= 1.3.1.5
    - async >= 2.2.1
    - ekg >= 0.4.0.15
    - ekg-core >= 0.1.1.4
    - clock >= 0.7.2

tests:
  od-indexer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - od-crawler
