name:                od-crawler
version:             0.1.0.0
github:              "agourlay/od-crawler"
license:             BSD3
author:              "agourlay"
maintainer:          "agourlay"
copyright:           "2019 Arnaud Gourlay"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/agourlay/od-crawler#readme>

default-extensions:
- OverloadedStrings
- LambdaCase

dependencies:
- base
- bytestring
- uri-encode
- http-conduit
- html-conduit
- xml-conduit
- text
- unordered-containers
- directory
- ekg
- ekg-core
- clock
- optparse-applicative
- streamly

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Werror
  - -fno-warn-orphans
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  od-crawler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - od-crawler

tests:
  od-indexer-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - od-crawler
    - hspec
    - hspec-discover
    - raw-strings-qq
